## 1. Why use NumPy ?

- Even though Python lists are great on their own, NumPy has a number of key features that give it great advantages over Python lists.

- One such feature is speed. When performing operations on large arrays NumPy can often perform several orders of magnitude faster than Python lists. This speed comes from the nature of NumPy arrays being memory-efficient and from optimized algorithms used by NumPy for doing arithmetic, statistical, and linear algebra operations.

- Another great feature of NumPy is that it has multidimensional array data structures that can represent vectors and matrices.

- NumPy is optimized for matrix operations and it allows us to do Linear Algebra operations effectively and efficiently, making it very suitable for solving machine learning problems.

- Another great advantage of NumPy over Python lists is that NumPy has a large number of optimized built-in mathematical functions. These functions allow you to do a variety of complex mathematical computations very fast and with very little code (avoiding the use of complicated loops) making your programs more readable and easier to understand.


## 2. Create NumPy ndarrays

Generally, there are 2 ways to create NumPy arrays:

1. First, using NumPy's arrays function to create them from other array-like object such as python lists.

2. Second, using a variety of built-in NumPy functions that generate specific types of arrays.


In [ ]:
import numpy as np

In [ ]:
# create an array using a list:
x = np.array([1, 2, 3, 4, 5])

In [ ]:
# Create a 2D array from lists:
Y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [ ]:
# the types of elemnts of that array:
x.dtype

dtype('int64')

In [ ]:
# Shape of an array:
Y.shape

(4, 3)

In [ ]:
# size of an array (number of elements):
Y.size

12

## 3. Using Built-in Functions to Create ndarrays

In [ ]:
# create an array of zeros with specific shape:
X = np.zeros((3,4))
X

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# create an array of ones of with specific shape:
X = np.ones((4,5))
X

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# crerate an array of a specific constant with specific shape:
X = np.full((4, 3), 5)
X

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
# create an indentity matrix :
X = np.eye(5)
X

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# create a diagonal matrix:
X = np.diag([10, 20, 30, 40])
X

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 40]])

In [ ]:
# create a vector using range:
x = np.arange(1, 14, 3)
x

array([ 1,  4,  7, 10, 13])

In [ ]:
# line space takes 3 arguments start, stop and n. This returns n evenly spaced number from start to stop:
# stop and start are inclusive:
x = np.linspace(0, 25, 10)
x

array([ 0.        ,  2.77777778,  5.55555556,  8.33333333, 11.11111111,
       13.88888889, 16.66666667, 19.44444444, 22.22222222, 25.        ])

By Combining the np.arange and np.linespace with reshape function we can get a 2D array.

In [ ]:
# create a matrix with np.arange :
X = np.arange(20).reshape(4,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
X = np.linspace(0, 50, 10, endpoint=False).reshape(5, 2)
X

array([[ 0.,  5.],
       [10., 15.],
       [20., 25.],
       [30., 35.],
       [40., 45.]])

In [ ]:
# create random matrices:
X = np.random.random((3,3))
X

array([[0.63095603, 0.21123089, 0.19675426],
       [0.97679386, 0.42876925, 0.33031632],
       [0.61233567, 0.94834973, 0.70483264]])

In [ ]:
X =np.random.randint(4, 15, (3,2))
X

array([[4, 5],
       [7, 7],
       [4, 8]])

## 4. Accessing, Deleting, and Inserting Elements Into ndarrays

### Accessing:


In [ ]:
x = np.array([1, 2, 3, 4, 5])

In [ ]:
# modifiy an element in the x vector:
x[3] = 20
x

array([ 1,  2,  3, 20,  5])

In [ ]:
# accessing an element in a matrix:
X = np.arange(1, 10).reshape(3, 3)
X[0][0], X[0,0]

(np.int64(1), np.int64(1))

### Deleting:

We can delete elemnts using NumPy's delete function. This function takes in an array list of indices to delete and an axis to delete from.

For one array the ranks keyword is not required, for 2D array 0 for row and 1 for cols.

In [ ]:
# Create a matrix:
Y = np.arange(1, 10).reshape(3, 3)
# delete the first row:
W = np.delete(Y, 0, axis=0)
W

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
# delete the first and third cols:
V = np.delete(Y, [0, 2], axis=1)
V

array([[2],
       [5],
       [8]])

### Inserting:

We can add values to NumPy array using the append function.

This function takes an array, list of elements to append and the axis to append it on.

In [ ]:
# Append elts to a vector:
x = np.array([1, 2, 3, 4, 5])
x = np.append(x, [6, 7])
x

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Append a row to a matrix:
X = np.arange(1, 10).reshape(3, 3)
W = np.append(X, [[10, 11, 12]], axis=0)
W

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# Append a col to a matrix:
V = np.append(X, [[10], [11], [12]], axis=1)
V

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

### Stacking:

In [ ]:
x = np.array([1, 2])
Y = np.array([[3, 4], [5, 6]])


In [ ]:
# Vstacking:
Z = np.vstack((x, Y))
Z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# hstacking:
W = np.hstack((Y, x.reshape(2, 1)))
W

array([[3, 4, 1],
       [5, 6, 2]])

## 5. Slicing ndarrays

In genearl, you will come across 3 ways of slicing:

**x[start:end]**

**X[start:]**

**X[:end]**

*Note*: Slicing only creates a view for the original array. To avoid this we use: np.copy(slicing)

In [ ]:
# Slicing with 2D array:
X = np.arange(1, 21).reshape(4,5)
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
# Slicing:
Z = X[1:4, 2:5]
Z

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [ ]:
Z = X[1:,2:]
Z

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [ ]:
# All the elments in the third col:
Z = X[:, 2]
Z

array([ 3,  8, 13, 18])

In [ ]:
# Select the diag elemnts in a mtarix:
z = np.diag(X)
z

array([ 1,  7, 13, 19])

In [ ]:
# Select the diag elemnts in a mtarix shifting by k:
z = np.diag(X, k=1)
z

array([ 2,  8, 14, 20])

In [ ]:
# Extract only the unique numbers of an numpy array:
X = np.array([[1, 2, 3], [5, 2, 8], [1, 2, 3]])
u = np.unique(X)
u

array([1, 2, 3, 5, 8])

## 6.Boolean Indexing, Set Operations, and Sorting

### Boolean indexing:

There are many situations that we don't know the indices of the elements we want.

Boolean indexing can help us in these cases by helping us select elements using logical arguments instead of explicit indices.

In [ ]:
X = np.arange(25).reshape(5, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# boolean indexing to select elts grater than 10:
Z = X[X>10]
Z

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
# Assign the values between 10 and 17 to -1:
X[(X>10) & (X<17)] = -1
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, -1, -1, -1, -1],
       [-1, -1, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Set operations:

In [ ]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 8, 2, 4])

In [ ]:
# intersection:
np.intersect1d(x, y)

array([2, 4])

In [ ]:
# difference:
np.setdiff1d(x, y)

array([1, 3, 5])

In [ ]:
# union:
np.union1d(x, y)

array([1, 2, 3, 4, 5, 6, 7, 8])

### Sorting

When we use sort as method, the original array is changed.

When we use np.sort(), the original array still unchanged.

In [ ]:
x = np.random.randint(1, 11, size=(10,))
x

array([8, 7, 2, 1, 5, 7, 9, 5, 3, 5])

In [ ]:
# sorting using np.sort(): leave the original array unchanged:
z = np.sort(x)
z

array([1, 2, 3, 5, 5, 5, 7, 7, 8, 9])

In [ ]:
# sorting the array in place:
x.sort()
x

array([1, 2, 3, 5, 5, 5, 7, 7, 8, 9])

## 7. Arithmetic operations and Broadcasting

### Element wise operations


In [ ]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

In [ ]:
# Adding:
np.add(x, y), x + y

(array([ 6,  8, 10, 12]), array([ 6,  8, 10, 12]))

In [ ]:
# substract:
np.subtract(x, y), x - y

(array([-4, -4, -4, -4]), array([-4, -4, -4, -4]))

In [ ]:
# multiply:
np.multiply(x, y), x * y

(array([ 5, 12, 21, 32]), array([ 5, 12, 21, 32]))

In [ ]:
# divide:
np.divide(x, y), x / y

(array([0.2       , 0.33333333, 0.42857143, 0.5       ]),
 array([0.2       , 0.33333333, 0.42857143, 0.5       ]))

In [ ]:
# square root:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [ ]:
# exp:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [ ]:
# sum:
x.sum()

np.int64(10)

In [ ]:
# average:
x.mean()

np.float64(2.5)

In [ ]:
# max:
x.max()

np.int64(4)

NumPy sometimes uses something called broadcasting.

Broadcasting is a term used to describe how NumPy handles element-wise operations with arrays of different shapes.

In [ ]:
Y = np.arange(9).reshape(3, 3)
x = np.arange(3)

In [ ]:
# Adding:
Y + x

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])